apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: mini-project3
spec:
  refreshInterval: 1h          # 1시간마다 자동 갱신
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: backend-secret        # 생성될 K8s Secret 이름
  data:
  - secretKey: DB_HOST
    remoteRef:
      key: team01-mini-project3/backend
      property: DB_HOST
  - secretKey: DB_PASSWORD
    remoteRef:
      key: team01-mini-project3/backend
      property: DB_PASSWORD
  - secretKey: REDIS_HOST
    remoteRef:
      key: team01-mini-project3/backend
      property: REDIS_HOST