apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mini-project3
  annotations:
    # [2] IP 모드 사용 시 서비스 단위에서 헬스 체크 경로를 지정 (프론트엔드용)
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  # [3] IP 모드에서는 ClusterIP로도 충분하지만, 관습적으로 NodePort를 유지해도 무방합니다.
  type: NodePort 
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP